site_name: SanTest
theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - navigation.top
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - Accueil: index.md

  - Installation: install.md
  
  - Guide utilisateur:
    - utilisation/index.md
    - Répondre aux questionnaires: utilisation/01-repondre-questionnaires.md
    - Historique des résultats: utilisation/02-historique-resultats.md
    - Favoris et recherche: utilisation/03-favoris-recherche.md
    - Navigation et interface: utilisation/04-navigation-interface.md
  
  - Création de questionnaires:
    - creation-questionnaires/index.md
    - Premiers pas: creation-questionnaires/01-premiers-pas.md
    - Gestion des questions: creation-questionnaires/02-questions.md
    - Dimensions de scoring: creation-questionnaires/03-dimensions.md
    - Conseils personnalisés: creation-questionnaires/04-conseils.md
    - Finalisation: creation-questionnaires/05-finalisation.md
  
  - Configuration:
    - configuration/index.md
    - Importation: configuration/01-import.md
    - Types de questionnaires: configuration/02-types-questionnaires.md
    - Réinitialisation: configuration/03-reinitialisation.md
